app = "spotify-visualization"
primary_region = "lhr"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"
  PYTHON_VERSION = "3.11"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 2048

[deploy]
  strategy = "immediate"
  release_command = "pip install -r requirements.txt"

[build.args]
  PYTHON_VERSION = "3.11" 